#!/bin/bash
go build -o ./cmd/server/server ./cmd/server
go build -o ./cmd/agent/agent ./cmd/agent
  SERVER_PORT=8080
          ADDRESS="localhost:${SERVER_PORT}"
          TEMP_FILE="metrics-postgres.json"
         ./metricstest-darwin-amd64 -test.v -test.run=^TestIteration14$ \
            -agent-binary-path=cmd/agent/agent \
            -binary-path=cmd/server/server \
            -database-dsn='postgresql://Mr8:Rammstein12!@localhost:5432/yaproject_db' \
            -key="123456" \
            -server-port=$SERVER_PORT \
            -source-path=.
