#!/bin/bash
go build -o ./cmd/server/server ./cmd/server
go build -o ./cmd/agent/agent ./cmd/agent
./metricstest-darwin-amd64 -test.run=^TestIteration13*$ -agent-binary-path=./cmd/agent/agent -source-path=. -binary-path=./cmd/server/server -server-port=8080 -database-dsn='postgresql://Mr8:Rammstein12!@localhost:5432/yaproject_db'
