#!/bin/bash
go build -o ./cmd/server/server ./cmd/server
go build -o ./cmd/agent/agent ./cmd/agent
./metricstest-darwin-amd64 -test.run=^TestIteration3[AB]*$ -agent-binary-path=./cmd/agent/agent -source-path=. -binary-path=./cmd/server/server