#!/bin/bash
go build -o ./cmd/server/server ./cmd/server
go build -o ./cmd/agent/agent ./cmd/agent
./metricstest-darwin-amd64 -test.run=^TestIteration10*$ -agent-binary-path=./cmd/agent/agent -source-path=. -binary-path=./cmd/server/server -server-port=8080 -database-dsn='postgres://postgres:postgres@postgres:5432/praktikum?sslmode=disable'
